const test = () => {
  try {
    const message = 'This file is correct'
    console.log(message)
  } catch (e) {
    throw e
  }
}

test()
